dhcpd:
  image: joebiellik/dhcpd

  net: host

  volumes:
    # Config pass through
    - ./dhcpd.conf:/etc/dhcp/dhcpd.conf
    # Uncomment to persist leases, make sure a empty file exists first
    # - ./dhcpd.leases:/var/lib/dhcp/dhcpd.leases
